services:
  - type: web
    name: luxury-edits
    runtime: java
    plan: free

    buildCommand: ./mvnw clean package -DskipTests

    startCommand: java -jar target/*.jar

    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: my-parlour-db
          property: connectionString

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: my-parlour-db
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: my-parlour-db
          property: password

      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

      - key: ADMIN_USERNAME
        sync: false

      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: my-parlour-db
    databaseName: my_parlour
    user: my_parlour_user
    plan: free
    type: psql
